apply plugin: 'java'

version = '1.0.0'
group = 'com.glowingfederal.legacyprofiler'
archivesBaseName = 'legacy-profiler'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

jar {
    manifest {
        attributes 'Implementation-Title': 'Legacy Profiler',
                   'Implementation-Version': version,
                   'Automatic-Module-Name': 'com.glowingfederal.legacyprofiler'
    }
}
